---
- name: gather Cloud/OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_bios_version }}-{{ ansible_distribution }}.yml'
    - '{{ cloud_platform }}-{{ ansible_distribution }}.yml'

- name: install certbot-auto
  become: true
  copy:
    src: 'certbot-auto'
    dest: '/usr/local/bin/'
    mode: '0755'
    owner: '{{ USER.user }}'
    group: '{{ USER.user }}'

- name: create ssl certificate
  shell: 'certbot-auto certonly --standalone --email dev@harmony.one -d {{ domain }} -q --agree-tos'

- name: change owner of certificates
  become: true
  file:
    dest: '/etc/letsencrypt/{{ item }}'
    owner: '{{ USER.user }}'
    group: '{{ USER.user }}'
    recurse: yes
  with_items:
    - 'live'
    - 'archive'

- name: setup cron task renew ssl certificate
  cron:
    name: renew ssl certificate
    job: '/usr/local/bin/certbot-auto renew --quiet'
    minute: '0'
    hour: '3'
    day: '*'
    month: '*'
    weekday: '*'

- name: setup cron task reset ssl certificate permission
  cron:
    name: reset ssl certificate permission
    job: 'sudo chown -R {{ USER.user }}:{{ USER.user }} /etc/letsencrypt/{{ item }}'
    minute: '5'
    hour: '3'
    day: '*'
    month: '*'
    weekday: '*'
  with_items:
    - 'live'
    - 'archive'


# vim: set expandtab:ts=2