FROM node:14

WORKDIR /app

ENV NODE_ENV {{ network }}

{% if function == "vault" %}
ENV MODE vault
{% else %}
ENV MODE base
{% endif %}

COPY ./src /app/src
#COPY ./frontend /app/frontend
COPY package.json /app/package.json
#COPY package-lock.json /app/package-lock.json
COPY env.js /app/env.js
COPY tsconfig.json /app/tsconfig.json
COPY .env.{{ network }} /app/.env.{{ network }}
COPY proxy.js /app/proxy.js
COPY start.sh /app/start.sh

RUN npm i && npm run build
RUN npm i -g serve

CMD sh ./start.sh