---
- name: delete btc relayer repo
  file:
    path: '/home/{{ ansible_user }}/onebtc.relayer-client'
    state: absent
  ignore_errors: yes

- name: clone the repo onebtc.relayer-client
  git:
    repo: 'https://github.com/harmony-one/onebtc.relayer-client.git'
    dest: '/home/{{ ansible_user }}/onebtc.relayer-client'
    version: '{{ branch }}'

- name: copy dockerfile
  template:
    src: 'Dockerfile.be.j2'
    dest: '/home/{{ ansible_user }}/onebtc.relayer-client/Dockerfile'
    force: yes

- name: create directories for docker volumes
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '/home/{{ ansible_user }}/onebtc-disk'

- name: copy data to shared folder for relayers and vaults
  copy:
    src: '{{ item.src }}'
    dest: '/home/{{ ansible_user }}/onebtc-disk/{{ item.dest }}'
  with_items:
  - { src: '{{ function }}.{{ network }}.env.private', dest: '.env.private' }
  when: function == 'relayer' or function == 'vault'

- name: update repo env file with mongo container name
  lineinfile:
    path: '{{ item.src }}'
    regex: 'DATABASE_URL=mongodb://localhost:27017/MyDb'
    line: 'DATABASE_URL=mongodb://mongo:27017/MyDb'
    state: present
  with_items:
  - { src: '/home/{{ ansible_user }}/onebtc.relayer-client/.env.testnet'}
  - { src: '/home/{{ ansible_user }}/onebtc.relayer-client/.env.mainnet'}

- name: build or rebuild container image
  docker_image:
    name: harmonyone/hmy-btc-relayer:latest
    build:
      path: '/home/{{ ansible_user }}/onebtc.relayer-client'
      pull: yes
      nocache: yes
    source: build
    state: present
    force_source: yes

- name: stop mongodb for restart/update
  ignore_errors: yes
  docker_container:
    name: 'mongo'
    state: stopped

- name: 'start mongodb'
  docker_container:
    name: 'mongo'
    image: 'mongo:5.0.3'
    ports: '27017:27017' # temporary for Yuriy. final -> '127.0.0.1:27017:27017'
    volumes:
      - "/home/{{ ansible_user }}/mongodata:/data/db"
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"

- name: stop current container for update
  ignore_errors: yes
  docker_container:
    name: 'btc-relayer'
    state: stopped

- name: 'start hmy-btc-relayer:latest container'
  docker_container:
    name: 'btc-relayer'
    image: 'harmonyone/hmy-btc-relayer:latest'
    ports: '8080:8080'
    volumes:
      - '/home/{{ ansible_user }}/onebtc-disk/:/app/keys/'
    env: #env file used for acme companion
      VIRTUAL_HOST: "{{ domain }}"
      VIRTUAL_PORT: '8080'
      LETSENCRYPT_HOST: "{{ domain }}"
      LETSENCRYPT_EMAIL: 'devops@harmony.one'
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"

- name: wait container launched succeed
  wait_for:
    host: '0.0.0.0'
    port: '8080'
    delay: 15
    state: started

- name: prune legacy images/container for update
  docker_prune:
    containers: yes
    images: yes
    images_filters:
      dangling: false
    builder_cache: yes
  become: yes
  ignore_errors: yes
  #containers_filters:
  #  until: 24h

- name: clear secret files
  ignore_errors: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/home/{{ ansible_user }}/onebtc-disk/.env.private'