---
- hosts: '{{ inventory }}'

  roles:
  - role: geerlingguy.docker
    become: yes

  tasks:
  - name: gather OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - '{{ ansible_bios_version }}-{{ ansible_distribution }}.yml'
      - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}.yml'
      - '{{ cloud_platform }}-{{ ansible_distribution }}.yml'

  - name: install required packages
    package:
      name: '{{ item }}'
      state: present
    become: true
    with_items: '{{ PACKAGES }}'

  - name: install docker python packages for ansible manage docker
    become: yes
    pip:
      name: "{{ item }}"
    with_items:
      - docker
      - docker-compose

  - name: adding existing user '{{ ansible_user }}' to group docker
    become: yes
    user:
      name: '{{ ansible_user }}'
      groups: docker
      append: yes

  - name: reload service docker, in all cases
    become: yes
    systemd:
      name: docker
      state: restarted