---
- hosts: '{{ inventory }}'
  gather_facts: yes
  become: true

  tasks:
  - name: install harmony binary
    get_url: 
      url: "https://s3-us-west-1.amazonaws.com/pub.harmony.one/release/linux-x86_64/{{ bucket }}/static/harmony"
      dest: /usr/sbin/harmony
      mode: '0755'

  - name: install harmony.service
    copy:
      src: ptn/harmony.service
      dest: /etc/systemd/system/harmony.service

  - name: create /etc/harmony
    file:
      path: /etc/harmony
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0755'

  - name: install harmony.conf
    copy:
      src: ptn/harmony.conf
      dest: /etc/harmony/harmony.conf
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0644'

  - name: install blskeys
    copy:
      src: "keys/{{ host }}/blskeys/"
      dest: "/home/{{ ansible_user }}/.hmy/blskeys/"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
